### ISSUE TITLE
Start following me.

### ISSUE THREAD

**Issue by netzeroo** [yusefkarim/STM32F4-Projects#1]
Hey, I started coding in rust.
https://docs.rs/async-fs/1.0.1/async_fs/
^ useful versus normal file writes, better than tokio for file writing:

Check out this AVR guide with rust:
https://lights0123.com/blog/2020/07/25/async-await-for-avr-with-rust/

I might try polling, might need to create a 3d scanner or something.

**Comment by yusefkarim** [comment]
Hey,

Nice! I haven't worked on this in awhile, might start to pick it back up slowly before September comes. AVR yucky >:D.
